//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

module FSharpVSPowerTools.Resources 
open System
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [<global.System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>]
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute ()>]
    [<global.System.Runtime.CompilerServices.CompilerGeneratedAttribute ()>]
    [<global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute ("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>]
    type internal FSharpVSPowerTools () as self  =
        

        static let mutable resourceMan      = Unchecked.defaultof<global.System.Resources.ResourceManager>
        static let mutable resourceCulture  = Unchecked.defaultof<global.System.Globalization.CultureInfo>
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [<global.System.ComponentModel.EditorBrowsableAttribute (global.System.ComponentModel.EditorBrowsableState.Advanced)>]
        static member internal ResourceManager
            with get () : global.System.Resources.ResourceManager = 
                if obj.ReferenceEquals (resourceMan,null) then
                    let temp = new global.System.Resources.ResourceManager("FSharpVSPowerTools.Resources.FSharpVSPowerTools", typeof<FSharpVSPowerTools>.Assembly)
                    resourceMan <- temp
                resourceMan

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [<global.System.ComponentModel.EditorBrowsableAttribute (global.System.ComponentModel.EditorBrowsableState.Advanced)>]
        static member internal Culture 
            with get () : global.System.Globalization.CultureInfo = resourceCulture
            and  set v = resourceCulture <- v

        
        /// <summary>
        ///   Looks up a localized string similar to Visual F# Power Tools.
        /// </summary>
        static member internal  _110 
            with get () : string = FSharpVSPowerTools.ResourceManager.GetString ("110", resourceCulture)
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of additional commands for F# in Visual Studio.
        /// </summary>
        static member internal _112 
            with get () : string = FSharpVSPowerTools.ResourceManager.GetString ("112", resourceCulture)
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        static member internal  _400 
            with get () : System.Drawing.Icon = 
                FSharpVSPowerTools.ResourceManager.GetObject("400", resourceCulture) :?> System.Drawing.Icon
                



      //  private static global::System.Resources.ResourceManager resourceMan;
        
     //   private static global::System.Globalization.CultureInfo resourceCulture;
        

    //    internal FSharpVSPowerTools() {
     //   }

     //        internal static global::System.Resources.ResourceManager ResourceManager {
//            get {
//                if (object.ReferenceEquals(resourceMan, null)) {
//                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSharpVSPowerTools.Resources.FSharpVSPowerTools", typeof(FSharpVSPowerTools).Assembly);
//                    resourceMan = temp;
//                }
//                return resourceMan;
//            }
//        }
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Globalization.CultureInfo Culture {
//            get {
//                return resourceCulture;
//            }
//            set {
//                resourceCulture = value;
//            }
//        }

//        internal static string _110 {
//            get {
//                return ResourceManager.GetString("110", resourceCulture);
//            }
//        }//        

        /// <summary>
        ///   Looks up a localized string similar to A collection of additional commands for F# in Visual Studio.
        /// </summary>
//        internal static string _112 {
//            get {
//                return ResourceManager.GetString("112", resourceCulture);
//            }
//        }
//        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
//        internal static System.Drawing.Icon _400 {
//            get {
//                object obj = ResourceManager.GetObject("400", resourceCulture);
//                return ((System.Drawing.Icon)(obj));
//            }
//        }
